### ISSUE TITLE
Create README with setup instructions

### ISSUE THREAD

**Issue by vanshb03** [LordFarquaadtheCreator/health-hopper#12]
@LordFarquaadtheCreator 

#### Issue Description:
The repository currently lacks a README file, making it difficult for new users to set up and use the program. A README should be created with detailed instructions on how to set up the program, including any dependencies that need to be installed, configuration steps, and how to run the program.

#### Proposed Solution:
1. Make amends to the existing `README.md` file in the root of the repository.
2. Include a brief description of the project.
3. List any dependencies that need to be installed, along with instructions on how to install them.
4. Provide detailed setup instructions, including any configuration steps that need to be taken.
5. Include instructions on how to run the program, including any command-line arguments that can be used.
6. Lastly, add information on how to contribute to the project.

**Comment by LordFarquaadtheCreator** [comment]
🫡

**Comment by LordFarquaadtheCreator** [comment]
done - thanks for the advice!
