### ISSUE TITLE
Create Labels for Open Source Contribution

### ISSUE THREAD

**Issue by vanshb03** [LordFarquaadtheCreator/health-hopper#13]
@LordFarquaadtheCreator 
#### Issue Description:
To streamline the contribution process, it would be beneficial to create a set of labels for issues in our repository. These labels can help contributors identify the type of issue or task, making it easier for them to find tasks they are interested in and capable of completing. 

#### Proposed Solution:
1. Create a set of labels such as `bug`, `enhancement`, `documentation`, `beginner-friendly`, `good-first-issue` `help-wanted`, etc., to categorize issues.
2. Assign these labels to relevant issues in the repository to help contributors identify suitable tasks.
3. Include a guide in the repository's CONTRIBUTING.md file explaining the meaning and use of each label.

#### Additional Information:
Hi :)

**Comment by LordFarquaadtheCreator** [comment]
`CONTRIBUTING.md` created
